#                            -*- mode: org; -*-
#
#+TITLE:                README for OpenFOAM-3.0.1
#+AUTHOR:               The OpenFOAM Foundation
#+DATE:                     15th December 2015
#+LINK:                  http://www.openfoam.org
#+OPTIONS: author:nil ^:{}
# Copyright (c) 2015 OpenFOAM Foundation.

* About OpenFOAM
  OpenFOAM is a free, open source computational fluid dynamics (CFD) software
  package released by the OpenFOAM Foundation. It has a large user base across
  most areas of engineering and science, from both commercial and academic
  organisations. OpenFOAM has an extensive range of features to solve anything
  from complex fluid flows involving chemical reactions, turbulence and heat
  transfer, to solid dynamics and electromagnetics.

* Copyright
  OpenFOAM is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  See the file =COPYING= in this directory or
  [[http://www.gnu.org/licenses/]], for a description of the GNU General Public
  License terms under which you can copy the files.

* [[http://www.OpenFOAM.org/git.php][Download and installation instructions]]
* [[http://www.OpenFOAM.org/docs][Documentation]]
* [[http://www.OpenFOAM.org/bugs][Reporting bugs in OpenFOAM]]
* [[http://www.openfoam.org/contact][Contacting the OpenFOAM Foundation]]

1) icoUncoupledKineticParcelSRFFoam
A Lagrangian particle tracker for single rotating frames of reference i.e pimpleFoam
The icoUncoupledKineticParcelFoam solver available in Open∇FOAM® Build: 3.0.1-d8a290b55d28, is not able to handle the forces originating from the rotating frame forces (SRFForce) because it was made for geometries in a stationary reference frame. However, since the geometry is rotating here because the SRF or the single rotating frame solvers were used, a few corrections had to made. The corrections made would ensure that the resulting velocity and the position of the particle is in accordance with the rotating frame i.e the particle’s position and velocity would be output in terms of relative velocity and relative positions.
